spring:
  datasource:
    name: dev
    url: jdbc:mysql://xxx.xxx.xxx.xxx:xxxx/manage?useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&allowMultiQueries=true
    username: xxxx
    password: xxxx
  redis:
    database: 0
    host: 47.110.34.237
    port: 6379
    password: 123456