spring:
  datasource:
    name: dev
#    url: jdbc:mysql://172.19.216.49:3308/manage?useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&allowMultiQueries=true
#    url: jdbc:mysql://192.168.179.128:3306/manage?useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&allowMultiQueries=true
#    username: root
#    password: 123456
    url: jdbc:mysql://47.110.34.237:3306/manage?useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&allowMultiQueries=true
    username: root
    password: Ztt@@520
  redis:
    database: 0
    host: 47.110.34.237
    port: 6379
    password: 123456