spring:
  datasource:
    name: dev2
    url: jdbc:mysql://192.168.28.129:3306/manage?useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&allowMultiQueries=true
    username: root
    password: 123456
  redis:
    database: 0
    host: 192.168.28.129
    port: 6379
    password: 123456